FROM rhel7
USER root
RUN yum -y update && yum -y install curl nmap tar && yum clean all
RUN mkdir -p /mattermost/data

RUN curl https://releases.mattermost.com/3.4.0/mattermost-team-3.4.0-linux-amd64.tar.gz | tar -xvz

RUN rm /mattermost/config/config.json && chown 1001:root -R /mattermost && chmod -R g+w,o+w /mattermost 
COPY config.template.json /

COPY docker-entry.sh /
RUN chmod +x /docker-entry.sh
ENTRYPOINT ["/docker-entry.sh"]

USER 1001

EXPOSE 80
